### ISSUE TITLE
    assert new_strategy in _all_sharing_strategies AssertionError

### ISSUE THREAD

**Issue by xdtxAM** [JonasGeiping/data-poisoning#1]
(poising) bash-3.2$ python brew_poison.py --recipe --recipe gradient-matching
Traceback (most recent call last):
  File "/Users/dongqinuo/Desktop/demo/data-poisoning/brew_poison.py", line 24, in <module>
    import forest
  File "/Users/dongqinuo/Desktop/demo/data-poisoning/forest/__init__.py", line 3, in <module>
    from forest.witchcoven import Witch
  File "/Users/dongqinuo/Desktop/demo/data-poisoning/forest/witchcoven/__init__.py", line 2, in <module>
    from .witch_matching import WitchGradientMatching, WitchGradientMatchingNoisy, WitchGradientMatchingHidden, WitchMatchingMultiTarget
  File "/Users/dongqinuo/Desktop/demo/data-poisoning/forest/witchcoven/witch_matching.py", line 8, in <module>
    from .witch_base import _Witch
  File "/Users/dongqinuo/Desktop/demo/data-poisoning/forest/witchcoven/witch_base.py", line 10, in <module>
    from ..victims.victim_single import _VictimSingle
  File "/Users/dongqinuo/Desktop/demo/data-poisoning/forest/victims/__init__.py", line 4, in <module>
    from .victim_distributed import _VictimDistributed
  File "/Users/dongqinuo/Desktop/demo/data-poisoning/forest/victims/victim_distributed.py", line 14, in <module>
    from .victim_single import _VictimSingle
  File "/Users/dongqinuo/Desktop/demo/data-poisoning/forest/victims/victim_single.py", line 16, in <module>
    from .victim_base import _VictimBase
  File "/Users/dongqinuo/Desktop/demo/data-poisoning/forest/victims/victim_base.py", line 11, in <module>
    torch.multiprocessing.set_sharing_strategy(SHARING_STRATEGY)
  File "/Users/dongqinuo/anaconda3/envs/poising/lib/python3.10/site-packages/torch/multiprocessing/__init__.py", line 58, in set_sharing_strategy
    assert new_strategy in _all_sharing_strategies
AssertionError

**Comment by JonasGeiping** [comment]
I assume this is a question concerning why this would happen?

You are using an unsupported OS, probably windows or mac. To fix this error, set a sharing strategy in line https://github.com/JonasGeiping/data-poisoning/blob/13a2a7e3b0c208afacb76530a135e26a72fe9d64/forest/consts.py#L9
that fits your OS. `SHARING_STRATEGY = 'file_system'` will probably do the trick.
